### PR TITLE
[MNT] - Small formatting updates

### PR DESCRIPTION
**Pull request by TomDonoghue**
Thanks for contributing. If this is your first time,
make sure to read the [contributing guide.](https://github.com/mne-tools/mne-python/blob/main/CONTRIBUTING.md)

PR Description
--------------

As I was looking through the module to familiarize myself with the codebase, I made some minor tweaks & fixes to some small formatting things I noticed. 

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Review by mscheltienne — APPROVED** [review]

**Review by adam2392 — APPROVED** [review]

**Comment by mscheltienne** [comment]
@adam2392 Weird, `flake8` should not complain at 79 characters. I'll check the configuration files when I have time.

**Comment by mscheltienne** [comment]
@TomDonoghue Thanks for the syntax fixes, will merge once the CIs come back green.

**Comment by adam2392** [comment]
> @adam2392 Weird, `flake8` should not complain at 79 characters. I'll check the configuration files when I have time.

Weird... checking rn!

**Comment by adam2392** [comment]
I'ma push up some consolidation changes of the config files to see if this resolves things.

**Comment by adam2392** [comment]
Thanks @TomDonoghue !

**Pull request merged**
