### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by mscheltienne**
@adam2392 Could you add me to the test-pypi package? https://test.pypi.org/project/mne-icalabel/
I'd like to make sure everything works before I cut a new release, which will be compatible with MNE 1.6

### CODE REVIEW

**Comment by adam2392** [comment]
Done!

**Comment by mscheltienne** [comment]
Hmm, still getting `The user 'mscheltienne' isn't allowed to upload to project 'mne-icalabel'.`.

**Comment by mscheltienne** [comment]
Nevermind, got it, thanks

**Comment by adam2392** [comment]
Did you have a confirmation email?

**Pull request merged**
