### PR TITLE
[DOC] Use the mne-python style.css for better light/dark theme support

### PR DESCRIPTION
**Pull request by mscheltienne**
Updated `conf.py` and `style.css` based on what I found on MNE main.

### CODE REVIEW

**Comment by mscheltienne** [comment]
It builds, looks a bit better but not yet as well as `mne-python`.

**Review by adam2392 — APPROVED** [review]
LGTM.

Style fix should be fixed with merge on main

**Comment by mscheltienne** [comment]
I still want to look a bit into this one, I probably forgot to copy-paste a couple of stuff.

For the clean-up in `conf.py`, I did not remove anything, just moved around stuff and structured in sections the file:

- project settings
- sphinx settings
- HTML theme settings
- one section / extension settings

**Comment by mscheltienne** [comment]
I'll merge if doc is green, it's missing only one feature from `mne-python`, the nice render of type x-ref and double backticks with a difference background/formatting:

image

But I did not figure out where it was 😞

**Pull request merged**
