### PR TITLE
sidecar .json file saved separately

### PR DESCRIPTION
**Pull request by anandsaini024**
Used suffix 'digitizer' to save it separately from the other components label .tsv file in mne_iclabel/annotations/mara.py

### CODE REVIEW

**Comment by adam2392** [comment]
Sorry I'm not 100% following here. What is the goal of this change @anandsaini024 ?

**Comment by anandsaini024** [comment]
> Sorry I'm not 100% following here. What is the goal of this change @anandsaini024 ?

The file mara.py in [improve_icalabel](https://github.com/adam2392/improve_icalabel)/[mnestudy](https://github.com/adam2392/improve_icalabel/tree/master/mnestudy)/[ica_to_bids](https://github.com/adam2392/improve_icalabel/tree/master/mnestudy/ica_to_bids)/ was not writing all the files in the output directory. There were minor errors and those are corrected. 

Although, It still does not give the desired output as the number of component column is repeating in each iteration https://github.com/mne-tools/mne-icalabel/blob/f740a593bdcbb1c0d390216270be6af2faf522fc/mne_icalabel/annotation/bids.py#L163. You can run the mara.py to check the output. it does not through an error now.

**Comment by mscheltienne** [comment]
I'll have to check.. but this change does not make sense to me either :/

**Comment by anandsaini024** [comment]
> I'll have to check.. but this change does not make sense to me either :/

This change is to generate a sidecar in .json format apart from the .tsv file. Earlier this was not able to generate a separate .json file because https://github.com/mne-tools/mne-icalabel/blob/f740a593bdcbb1c0d390216270be6af2faf522fc/mne_icalabel/annotation/bids.py#L86-L89 update_sidecar_json only works if it's a json file. Basically there was only one file which is .tsv before this change (atleast on my computer). Please check and let me know if it was unnecessary.

**Pull request closed without merging**
