### PR TITLE
Update configuration and documentation build

### PR DESCRIPTION
**Pull request by mscheltienne**
I'm updating the configuration and the documentation build to run and deploy through github-actions, which I'm more familiar with.

It should help me maintain more actively this repository by having a configuration closer to 'mne-lsl' and to my other projects. 

Some bugs like the version selection have been present for a while, and are unfixed partially because I don't have the time to look through the current settings and configuration.

Also, I will open a second PR with python 3.12 support, and I'll cut a release for MNE 1.6 support.

### CODE REVIEW

**Comment by adam2392** [comment]
We are removing circleCI entirely right?

**Comment by mscheltienne** [comment]
Yes, I'm dropping it entirely. We had CI failures on this repository for the past 2 months, and neither of us had the time to fix those. My hope is that by using tools I'm familiar with, I can pick-up maintenance of this repository with a minimum overhead.

Sounds good to you?

**Comment by adam2392** [comment]
Ah okay. Sounds good!

**Comment by mscheltienne** [comment]
@adam2392 @larsoner Could you give me admin rights on this repository? I'd like to check that the secrets are in-line with the workflows.

**Comment by larsoner** [comment]
@mscheltienne done!

**Pull request merged**
