### PR TITLE
[ENH] Add API for bids pipeline annotating

### PR DESCRIPTION
**Pull request by adam2392**
PR Description
--------------

Addresses the API needed for the annotation GUI to interface with BIDS files of #12 

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by mscheltienne** [comment]
So simple, I love it :) The API from `mne-bids` looks super easy to re-use!

**Comment by mscheltienne** [comment]
Does this allow for a component to be labeled with different labels by different authors?

**Comment by adam2392** [comment]
Unfortunately no...

So I would say perhaps the tsv file stores the "final annotation" and optionally a score produced if it was an automated method

Perhaps what is better is a JSON, where there is a dict of lists with keys:

- component
- author
- label
- date
- (optional but idk how to get it) expertise

And then someone can leverage the JSON to formulate the "labels" training/testing dataset.

**Comment by mscheltienne** [comment]
Yes, I think that would be better 👍

**Comment by adam2392** [comment]
@sappelhoff and @hoechenberger I know BIDS isn't set yet, but wdyt about this for ICA derivatives to handle the problem of annotating labels manually? Anything you think we might be missing?

If this works well, perhaps it'll be a good explicit use case for BIDS-EEG-Derivatives to see and use for their specification for ICA.

**Review by sappelhoff — COMMENTED** [review]
I think as long as you mark this as "experimental / development" (with regards to BIDS) it can spark further discussion in https://github.com/bids-standard/bep021/issues/5 and https://bids.neuroimaging.io/bep021 :+1:

**Pull request merged**
