### PR TITLE
[DOC] Replace sphinx.ext.viewcode with sphinx.ext.linkcode

### PR DESCRIPTION
**Pull request by mscheltienne**
Let's see if it works 🤞

### CODE REVIEW

**Comment by mscheltienne** [comment]
Looks like it's working (I checked each element on the API page on the CircleCI artifacts). The style check is fixed in #101.
@adam2392 Merge if happy.

**Comment by mscheltienne** [comment]
Merging as I'm also updating the theme in another PR and I'd like to pull the changes. Let me know if you want to revert.

**Comment by adam2392** [comment]
Jw what is the diff between view code and link code? @mscheltienne

**Comment by mscheltienne** [comment]
Take the 'source' button on one of the function from the API, e.g. https://mne.tools/mne-icalabel/dev/generated/mne_icalabel.label_components.html#mne_icalabel.label_components
With viewcode, it links to a page of the website which renders a copy-paste of the function code. 
With linkcode, it links to the lines which correspond to the function on GitHub. 

Try it out by taking the same function on the latest release of the website and on the version 0.3, e.g.

viewcode: https://mne.tools/mne-icalabel/stable/generated/mne_icalabel.label_components.html#mne_icalabel.label_components
 linkcode: https://mne.tools/mne-icalabel/dev/generated/mne_icalabel.label_components.html#mne_icalabel.label_components

**Comment by adam2392** [comment]
Oh very cool!

**Pull request merged**
